# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # making a modification to load a Vagrantfile.local if it exists
  #   this will let me add local modifications if I need to outside of this repo
  # https://stackoverflow.com/a/53490858
  local_mods = './Vagrantfile.local'
  # https://stackoverflow.com/a/35769926
  eval File.read(local_mods) if File.exists?(local_mods)

  config.vm.synced_folder "~/src/", "/coding", create: true
  # install python so ansible is happy
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "pre-prov.yml"
  end
  # actually provision the machine to how I like
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "prov.yml"
  end
  # customization per project (change the * to the project name)
  # config.vm.provision :ansible do |ansible|
  #   ansible.playbook = "prov-*.yml"
  # end
end
