contact_links:
  - name: Migrated Repo to GitLab
    url: https://gitlab.com/elreydetoda-infra/iac/vagrant-files
    about: Feedback related with CodeQL CLI, languages, libraries, documentation, etc.
