# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "elrey741/kali-linux_amd64"
  config.vm.synced_folder ENV["DATADIR"], "/data"
  config.vm.provider "virtualbox" do |vb|
    vb.name = ENV["VMNAME"]
    # Display the VirtualBox GUI when booting the machine
    vb.gui = ENV["GUI"]
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end
end
