# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "~/src/", "/coding", create: true
  config.vm.provision "shell", path: "prov.sh"
end
