# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jhcook/fedora27"
  # allow applications to be open through ssh
  config.ssh.forward_x11 = true
  # config how I like
  config.vm.provision "shell", path: "prov.sh"

  # making a modification to load a Vagrantfile.local if it exists
  #   this will let me add local modifications if I need to outside of this repo
  # https://stackoverflow.com/a/53490858
  local_mods = './Vagrantfile.local'
  # https://stackoverflow.com/a/35769926
  eval File.read(local_mods) if File.exists?(local_mods)
end
