- hosts: all
  become: yes
  tasks:

  - name: installing all packages
    block:

      # commenting out because: https://github.com/elreydetoda/packer-kali_linux/issues/44
      # - name: remove docker to use docker snap later
      #   apt:
      #     state: absent
      #     name:
      #       - docker-ce

      - name: installing apt packages
        apt:
          state: present
          name:
            - vim-gtk3
            - glances
            - jq
            - snapd
            - xclip
            - python3-pip
            - python3-venv

      - name: installing python tools
        pip:
          state: present
          name:
            - pipenv
            - pipx # based on @byt3bl33d3r's recommendation: https://youtu.be/ieyRV9zQd2U

      - name: cleaning up kali
        apt:
          autoremove: yes

      - name: installing normal snap packages
        snap:
          name:
            # commenting out because: https://github.com/elreydetoda/packer-kali_linux/issues/44
            # - docker
            - postman

      - name: installing classic snap packages
        snap:
          classic: yes
          name:
            - go
            - code

  - name: adding docker deps
    block:

      - name: adding docker group
        group:
          system: yes
          name: docker

      - name: adding vagrant to docker group
        user:
          name: vagrant
          groups: docker
          append: yes

  - name: configuring other customizations
    block:

      - name: setting up tools
        block:

          - name: check if msfdb has been initialized
            stat:
              path: /usr/share/metasploit-framework/config/database.yml
            register: msfdb_result

          - name: initializing metasploit framework
            command: msfdb init
            when: not msfdb_result.stat.exists

          - name: update nmap script db
            command: nmap --script-updatedb

          - name: update recon-ng marketplace
            command: recon-ng -r /vagrant/tools/recon-ng/update-install_marketplace.rf
            become: yes
            become_method: su
            become_user: vagrant
            args:
              creates: ~vagrant/.recon-ng/modules.yml

          - name: enabling and starting other services
            systemd:
              enabled: yes
              state: started
              name: "{{ item }}"
            loop:
              - postgresql
              # - snap.docker.dockerd.service

          - name: setting vim as editor
            alternatives:
              name: editor
              path: /usr/bin/vim.gtk3

      - name: configuring home settings
        block:

          - name: configuring bash settings
            block:

              - name: copy custom PS1 prompt
                copy:
                  src: ./bash_prompt
                  dest: ~vagrant/.bash_aliases
                  owner: vagrant
                  group: vagrant
                  mode: 0644

              - name: removing kali prompt
                copy:
                  dest: ~vagrant/.hushlogin
                  owner: vagrant
                  group: vagrant
                  mode: 0644
                  content: ""

              - name: set vi mode for bash but Ctrl + l
                copy:
                  dest: ~vagrant/.inputrc
                  owner: vagrant
                  group: vagrant
                  mode: 0644
                  content: |
                    set editing-mode vi
                    $if mode=vi

                    set keymap vi-command
                    # these are for vi-command mode
                    Control-l: clear-screen

                    set keymap vi-insert
                    # these are for vi-insert mode
                    Control-l: clear-screen
                    $endif
